eis/urls.py
from django.conf.urls import patterns, include, url


from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'eis.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^emp/', include('emp.urls',namespace="emp")),
    url(r'^admin/', include(admin.site.urls)),
)

emp/urls.py
from django.conf.urls import patterns,url
from emp.views import Department_List,Employee_List
from emp import views

dep_list = Department_List.as_view({
    'get': 'list',
    'post': 'create'
},)
dep_detail = Department_List.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
emp_list = Employee_List.as_view({
    'get': 'list',
    'post': 'create'
},)
emp_detail = Employee_List.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
    'delete': 'destroy'
})
urlpatterns=patterns('',url(r'^$',views.IndexView.as_view(), name="index"),
                       # url(r'^employee_details/$', views.List.as_view(), name="List"),
                       # url(r'^department_details/$',views.List1.as_view(),name="List1"),
                        url(r'^department/$',dep_list,name='department'),
                        url(r'^department/(?P<pk>[0-9]+)/$',dep_detail,name='department1'),
                        url(r'^employee/$',emp_list,name='employee'),
                        url(r'^employee/(?P<pk>[0-9]+)/$',emp_detail,name='employee1'),
                        url(r'^department_list/$',views.Department_list.as_view(),name="department_list"),
                        url(r'^add_department/$',views.Add_department.as_view(),name="add_department"),
                        url(r'^view_details/$',views.View_department.as_view(),name="view_details"),
                        url(r'^update_department/$',views.Update_department.as_view(),name="update_department"),
                        url(r'^employee_list/$',views.Employee_list.as_view(),name="employee_list"),
                        url(r'^add_employee/$',views.Add_employee.as_view(),name="add_employee"),
                        url(r'^employee_detail/$',views.View_employee.as_view(),name="employee_detail"),
                        url(r'^update_employee/$',views.Update_employee.as_view(),name="update_employee"),
                        url(r'^index/$',views.Home.as_view(),name="home"),
                     )

emp/models.py
from django.db import models

class Department(models.Model):
    department_id=models.AutoField(primary_key=True)
    department_name=models.CharField(max_length=200)

    def __unicode__(self):
        return self.department_name

class Employee(models.Model):
    employee_id=models.AutoField(primary_key=True)
    ename=models.CharField(max_length=200)
    age=models.IntegerField(default=0)
    emailid=models.EmailField(max_length=200)
    mobno=models.IntegerField()
    designation=models.CharField(max_length=20)
    department=models.ForeignKey(Department, on_delete=models.CASCADE)

emp/views.py
from bsddb import db
from django.views import generic

from emp.models import Employee,Department
from emp.serializers import DepSerializer, EmployeeSerializer
from rest_framework import viewsets


class Department_List(viewsets.ModelViewSet):
    model = Department
    queryset = Department.objects.all()
    serializer_class = DepSerializer

class Employee_List(viewsets.ModelViewSet):
    model = Employee
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

class IndexView(generic.TemplateView):
    template_name = 'emp/demo.html'

class Home(generic.TemplateView):
    template_name = 'emp/home.html'

"""class List1(generic.ListView):
  #  context_object_name = 'depl'
   # template_name = 'emp/department_details.html'
    template_name = 'emp/demo.html'
    model=Department
   # def get_queryset(self):
    #   return Department.objects.all()

class List(generic.ListView):
    #context_object_name = 'empl'
    template_name = 'emp/employee_details.html'
    model = Employee
    #def get_queryset(self):
     #  return Employee.objects.all()  """

class Department_list(generic.TemplateView):
    template_name = 'emp/department_list.html'

class Add_department(generic.TemplateView):
    template_name = 'emp/add_department.html'

class View_department(generic.TemplateView):
    template_name = 'emp/view_details.html'

class Update_department(generic.TemplateView):
    template_name = 'emp/update_department.html'

class Employee_list(generic.TemplateView):
    template_name = 'emp/employee_list.html'

class Add_employee(generic.TemplateView):
    template_name = 'emp/add_employee.html'

class View_employee(generic.TemplateView):
    template_name = 'emp/employee_detail.html'

class Update_employee(generic.TemplateView):
    template_name = 'emp/update_employee.html'

emp/templates/emp/add_department.html
 <h2 class="bg-info text-primary">Add New Departmnet</h2><hr>
        <table>
    <tr><td><label for="id_department">Department Name:</label></td><td><input type="text" name="department" id="id_department" class="department" /></td></tr>
        <tr><td></td><td><div id="error1"></div></td></tr>
            </table><br/><br/>

        <span class="btn btn-primary" ><a href="#/department_list/" style="color: #ffffff" >BACK</a></span>
        <span class="btn btn-primary" ><a href="#/add_department/" style="color: #ffffff" >ADD</a></span>
         <span class="btn btn-primary" ><a href="#/new_department/new/0/" style="color: #ffffff" >RESET</a></span>

 <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/loading_spinner.gif' width="64" height="64" /><br>Loading..</div>

emp/templates/emp/add_employee.html
 <div id="newemp" style="display: none">
      <h2 class="bg-info text-primary">Add New Employee Details</h2><hr>

        <table class="table table-bordered" style="width: 60%">
       <tr><th> Name:</th><td><input type="text" maxlength="30" name="e2" id="ename_new"/><div id="new1"></div></td></tr>
        <tr><th>  Age:</th><td><input type="text" maxlength="30" name="e3" id="age_new" /><div id="new2"></div></td></tr>
       <tr><th>  Email id:</th><td><input type="text" maxlength="30" name="e4" id="email_new"/><div id="new3"></div></td></tr>
        <tr><th> Mobile No:</th><td><input type="text" maxlength="30" name="e5" id="mob_new"/><div id="new4"></div></td></tr>
        <tr><th> Designation:</th><td><input type="text" maxlength="30" name="e6" id="designation_new"/><div id="new5"></div></td></tr>
        <tr><th> Department:</th><td><select name="e7" id="dropdepartment1"></select>
        </td></tr>

        </table>
      <span class="btn btn-primary" ><a href="#/employee_list/" style="color: #ffffff" >BACK</a></span>
    <span class="btn btn-primary"><a href="#/add_employee/" style="color:#ffffff">ADD</a></span>
     <span class="btn btn-primary"><a href="#/new_employee/new/0/" style="color:#ffffff">RESET</a></span>
     <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/loading_spinner.gif' width="64" height="64" /><br>Loading..</div>
</div>
 <div id="newerror" style="display: none"><h3 class="alert-info">
        Currently No Department.
         <span class="btn btn-primary"> <a href="#/department_list/" style="color:#ffffff"> Add department </a></span>
    </h3> </div>

emp/templates/emp/demo.html
{% extends "base.html" %}
{% block title %}Employee Information System{% endblock title %}
{% block js %}<script src="{{ STATIC_URL }}js/jquery-1.4.2.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}js/sammy.js" type="text/javascript" type="text/javascript"> </script>
<script src="{{ STATIC_URL }}js/demo.js" type="text/javascript" type="text/javascript"> </script>

{% endblock js %}
{% block content %}
    <div class="container-fluid">
    <hr>
    </div>
        <!--div id="header">
          <h1>Department details</h1>
        </div-->
        <center>
        <div id="main" class="container-fluid">

        </div>
        </center>

{% endblock content %}

emp/templates/emp/department_details.html
{% extends "base.html" %}
{% block title %}List of Department{% endblock title %}
{% block js %}
<script src="{{ STATIC_URL }}js/list1.js"> </script>
{% endblock js %}
{% block content %}
    <center>
    <hr><hr><hr>
        <div id="listdepartment">
     <h2 class="alert-warning">List of Department</h2><hr>

        <div id="error"></div>
        <table class="table table-bordered" id="department_list">
            <tr>

                <th>Department_Name</th>
                <th>View Employee details</th>
                <th>Edit details</th>
                <th> Delete??</th>
            </tr>
        </table>
        <b><div id="noData"></div></b><br/><br/>
    <input type="button" name="back" value="Back" class="btn btn-primary" id="back" />
    <input type="button" name="submit1" id="new" class="btn btn-primary" value="Add New Department?" />
    </div>
    <div id="adddepartment" style="display: none;">
    <h2 class="alert-warning">Add New Departmnet</h2><hr>
        <table>
    <tr><td><label for="id_department">Department Name:</label></td><td><input type="text" name="department" id="id_department" class="department" /></td></tr>
        <tr><td></td><td><div id="error1"></div></td></tr>
            </table><br/><br/>


        <input type="button" name="back" value="Back" class="btn btn-primary" id="back1" />
        <input type="button" name="add" value="Add" class="btn btn-primary" id="add" />
        <input type="button" name="reset" value="RESET" id="reset_dept" class="btn btn-primary" />
    </div>
    <div id="updatedepartment" style="display: none">

        <h2 class="alert-warning">Edit Department</h2>
        <table>
        <tr><td><label for="id_department1">Department Name:</label></td><td><input type="text" maxlength="30" name="dept" id="id_department1"  class="department" /></td></tr>
         <tr><td></td><td><div id="error2"></div></td></tr>
            </table><br/><br/>
        <input type="button" name="back" value="Back" class="btn btn-primary" id="back2" />
        <input type="button" name="update" value="Update" class="update btn btn-primary" />

        <br/><br/>
    </div>
     <div id="viewdetails" style="display: none">
        <h2 class="alert-warning" id="viewdet"></h2>
        <table class="table table-bordered" id="emp_list">
            <tr>

                <th>Name</th>
                <th>Age</th>
                <th>Email_id</th>
                <th>Mob_no</th>
                <th>Designation</th>
            </tr>
        </table>
         <input type="button" name="back" value="Back" class="btn btn-primary" id="back3" />
     </div>
    <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/demo_wait.jpg' width="64" height="64" /><br>Loading..</div>
</center>
{% endblock content %}

emp/templates/emp/department_list.html
  <h2 class="bg-info text-primary">List of Department</h2><hr>
       <div id="error"></div>
       <table class="table table-bordered" id="department_list">
            <tr>
                <th>Department_Name</th>
                <th>View Employee details</th>
                <th>Edit details</th>
                <th> Delete??</th>
            </tr>
       </table>
       <b><div id="noData"></div></b><br/><br/>


  <span class="btn btn-primary" ><a href="#/" style="color: #ffffff" >BACK</a></span>
    <span class="btn btn-primary"><a href="#/new_department/new/0/" style="color:#ffffff">ADD New Department</a></span>
   <!--input type="button" name="back" value="Back" class="btn btn-primary" id="back" />
  <input type="button" name="submit1" id="new" class="btn btn-primary" value="Add New Department?" /-->
    <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/loading_spinner.gif' width="64" height="64" /><br>Loading..</div>

emp/templates/emp/employee_detail.html
<div id="viewemployee">
         <h2 class="bg-info text-primary" id="viewemp"></h2><hr>

    <table class="table table-striped" id="viewtable" border="1" style="width: 60%">
        <tr></tr><tr></tr>
        <tr><th>Name</th><th id="ename2"></th></tr>
        <tr><th>Age</th><th id="age2"></th></tr>
        <tr><th>Email id</th><th id="email2"></th></tr>
        <tr><th>Mobile No</th><th id="mob2"></th></tr>
        <tr><th>Designation</th><th id="designation2"></th></tr>
        <tr><th>Department</th><th id="department2"></th></tr>
    </table>
     <span class="btn btn-primary" ><a href="#/employee_list/" style="color: #ffffff" >BACK</a></span>
    <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/loading_spinner.gif' width="64" height="64" /><br>Loading..</div>
    </div>

emp/templates/emp/employee_details.html
{% extends "base.html" %}
{% block title %}List of Employee{% endblock title %}
{% block js %}<!--script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script -->
    <script src="{{ STATIC_URL }}js/list.js"></script>
    {% endblock js %}
{% block content %}
    <center>
    <hr><hr><hr>

    <div id="employeelist" >
    <h2 class="alert-warning">List of Employees</h2>
    <table class="table table-bordered" id="emp_list1">
            <tr>

                <th>Name</th>
                <th>Age</th>
                <th>Email_id</th>
                <th>Mob_no</th>
                <th>Designation</th>
                 <th>Department</th>
                <th>View details</th>
                <th>Edit Record</th>
                 <th>Delete Record</th>
            </tr>
    </table>
        <input type="button" name="back" id="back" value="Back" class="btn btn-primary" />
       <input type="button" name="newwmployee" id="newemployee" value="Add New Employee?" class="btn btn-primary" />
 </div>
 <div id="editemployee" style="display: none">
      <h2 class="alert-warning">Edit Employee Details</h2><hr>

        <table class="table table-bordered" style="width: 60%">
       <tr><th> Name:</th><td><input type="text" maxlength="30" name="e2" id="ename1"/><div id="name1"></div></td></tr>
        <tr><th>  Age:</th><td><input type="text" maxlength="30" name="e3" id="age1" /><div id="name2"></div></td></tr>
       <tr><th>  Email id:</th><td><input type="text" maxlength="30" name="e4" id="email1"/><div id="name3"></div></td></tr>
        <tr><th> Mobile No:</th><td><input type="text" maxlength="30" name="e5" id="mob1"/><div id="name4"></div></td></tr>
        <tr><th> Designation:</th><td><input type="text" maxlength="30" name="e6" id="designation1"/><div id="name5"></div></td></tr>
        <tr><th> Department:</th><td><select name="e7" id="dropdepartment"></select>
        </td></tr>

        </table>
       <input type="button" name="back" id="back1" value="Back" class="btn btn-primary" />
        <input type="button" name="update" value="Update" class="update btn btn-primary" />

 </div>
    <div id="viewemployee" style="display: none">
         <h2 class="alert-warning" id="viewemp"></h2><hr>

    <table class="table table-striped" id="viewtable" border="1" style="width: 60%">
        <tr></tr><tr></tr>
        <tr><th>Name</th><th id="ename2"></th></tr>
        <tr><th>Age</th><th id="age2"></th></tr>
        <tr><th>Email id</th><th id="email2"></th></tr>
        <tr><th>Mobile No</th><th id="mob2"></th></tr>
        <tr><th>Designation</th><th id="designation2"></th></tr>
        <tr><th>Department</th><th id="department2"></th></tr>
    </table>
    <input type="button" name="back" id="back2" value="Back" class="btn btn-primary" />
    </div>
 <div id="newemp" style="display: none">
      <h2 class="alert-warning">Add New Employee Details</h2><hr>

        <table class="table table-bordered" style="width: 60%">
       <tr><th> Name:</th><td><input type="text" maxlength="30" name="e2" id="ename_new"/><div id="new1"></div></td></tr>
        <tr><th>  Age:</th><td><input type="text" maxlength="30" name="e3" id="age_new" /><div id="new2"></div></td></tr>
       <tr><th>  Email id:</th><td><input type="text" maxlength="30" name="e4" id="email_new"/><div id="new3"></div></td></tr>
        <tr><th> Mobile No:</th><td><input type="text" maxlength="30" name="e5" id="mob_new"/><div id="new4"></div></td></tr>
        <tr><th> Designation:</th><td><input type="text" maxlength="30" name="e6" id="designation_new"/><div id="new5"></div></td></tr>
        <tr><th> Department:</th><td><select name="e7" id="dropdepartment1"></select>
        </td></tr>

        </table>
       <input type="button" name="back" id="back3" value="Back" class="btn btn-primary" />
        <input type="button" name="add" id="add" value="Add" class="btn btn-primary" />
        <input type="button" name="Reset" value="reset" id="reset_emp" class="btn btn-primary" />

 </div>
    <div id="newerror" style="display: none">
        <pre class="alert-info">Currently there is no department. Add department first.</pre>

    </div>
    <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/demo_wait.jpg' width="64" height="64" /><br>Loading..</div>

</center>

{% endblock content %}

emp/templates/emp/employee_list.html
 <div id="employeelist" >
    <h2 class="bg-info text-primary">List of Employees</h2><hr/>
    <table class="table table-bordered" id="emp_list1">
            <tr>

                <th>Name</th>
                <th>Age</th>
                <th>Email_id</th>
                <th>Mob_no</th>
                <th>Designation</th>
                 <th>Department</th>
                <th>View details</th>
                <th>Edit Record</th>
                 <th>Delete Record</th>
            </tr>
    </table>
        <span class="btn btn-primary" ><a href="#/" style="color: #ffffff" >BACK</a></span>
    <span class="btn btn-primary"><a href="#/new_employee/new/0/" style="color:#ffffff">ADD New Employee</a></span>
     <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/loading_spinner.gif' width="64" height="64" /><br>Loading..</div>
 </div>

emp/templates/emp/home.html
    <!-- Page Content -->
<div class="container">

        <div class="row">

            <div class="col-lg-12">

                <h1 class="alert-dismissible text-primary">Welcome to Employee Information System</h1>
                <br />
                <p class="text-muted">This system manages employees and department details</p>
                  <hr />
                 <div id="header_ele"><ul >
        <li class="well" ><a   href="#/employee_list/" style="font-size: large" >Employee Details</a></li>
        <li class="well" ><a  href="#/department_list/" style="font-size: large">Department Details</a></li>
                       <hr />
    </ul></div>
            </div>
        </div>
</div>

emp/templates/emp/index.html
<div id="main">

{% block title %}Home page{% endblock title %}
</div>

emp/templates/emp/update_department.html
 <div id="updatedepartment">

        <h2 class="bg-info text-primary">Edit Department</h2>
        <table>
        <tr><td><label for="id_department1">Department Name:</label></td><td><input type="text" maxlength="30" name="dept" id="id_department1"  class="department" /></td></tr>
         <tr><td></td><td><div id="error2"></div></td></tr>
            </table><br/><br/>
       <span class="btn btn-primary" ><a href="#/department_list/" style="color: #ffffff" >BACK</a></span>
        <span class="btn btn-primary" ><a class="update" style="color: #ffffff" >UPDATE</a></span>

        <br/><br/>
      <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/loading_spinner.gif' width="64" height="64" /><br>Loading..</div>
    </div>

emp/templates/emp/update_employee.html
<div id="editemployee">
      <h2 class="bg-info text-primary">Edit Employee Details</h2><hr>

        <table class="table table-bordered" style="width: 60%">
       <tr><th> Name:</th><td><input type="text" maxlength="30" name="e2" id="ename1"/><div id="name1"></div></td></tr>
        <tr><th>  Age:</th><td><input type="text" maxlength="30" name="e3" id="age1" /><div id="name2"></div></td></tr>
       <tr><th>  Email id:</th><td><input type="text" maxlength="30" name="e4" id="email1"/><div id="name3"></div></td></tr>
        <tr><th> Mobile No:</th><td><input type="text" maxlength="30" name="e5" id="mob1"/><div id="name4"></div></td></tr>
        <tr><th> Designation:</th><td><input type="text" maxlength="30" name="e6" id="designation1"/><div id="name5"></div></td></tr>
        <tr><th> Department:</th><td><select name="e7" id="dropdepartment"></select>
        </td></tr>

        </table>
        <span class="btn btn-primary" ><a href="#/employee_list/" style="color: #ffffff" >BACK</a></span>
        <span class="btn btn-primary" ><a class="update" style="color: #ffffff" >UPDATE</a></span>

        <br/><br/>
      <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/loading_spinner.gif' width="64" height="64" /><br>Loading..</div>
    </div>

emp/templates/emp/view_details.html
 <div id="viewdetails">
        <h2 class="bg-info text-primary" id="viewdet"></h2>
        <table class="table table-bordered" id="emp_list">
            <tr>

                <th>Name</th>
                <th>Age</th>
                <th>Email_id</th>
                <th>Mob_no</th>
                <th>Designation</th>
            </tr>
        </table>
         <span class="btn btn-primary" ><a href="#/department_list/" style="color: #ffffff" >BACK</a></span>
     </div>
    <div id="wait" style="display:none;width:69px;height:89px;border:1px solid black;position:absolute;top:50%;left:50%;padding:2px;"><img src='{{ STATIC_URL }}images/loading_spinner.gif' width="64" height="64" /><br>Loading..</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} {% endblock title %}</title>
       {% block js %}{% endblock %}
    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <hr>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--a class="navbar-brand" href="#">Start Bootstrap</a -->
                   <a class="navbar-brand" href="#/">Employee Information System</a>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="header_ele">
                <ul class="nav navbar-nav">
                    <li>
                        <a  href="#/employee_list/">Employee Details</a>
                    </li>
                    <li>
                        <a href="#/department_list/">Department Details</a>
                    </li>

                </ul>
            </div>

            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    {% block content %}
    {% endblock content %}
    <!-- Footer -->
    <div class="container-fluid">
        <hr />
        <footer class="jumbotron">
            <div class="row">
                <div class="col-lg-12">
                    <p><center>Copyright &copy; Employee Information System 2014</center></p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery Version 1.11.0 -->
    <script src="{{ STATIC_URL }}js/jquery-1.11.0.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
</body>

</html>